<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>Philiprehberger.CsvKit</PackageId>
    <Version>0.1.2</Version>
    <Authors>Philip Rehberger</Authors>
    <Description>Lightweight CSV reader and writer with header mapping, type conversion, and streaming support.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>csv;parser;reader;writer;data</PackageTags>
    <RepositoryUrl>https://github.com/philiprehberger/dotnet-csv-kit</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
